/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.fileshare.views;

import fr.fileshare.dao.DocumentHandler;
import fr.fileshare.dao.HistoriqueHandler;
import fr.fileshare.dao.IDocumentHandler;
import fr.fileshare.dao.IMessageHandler;
import fr.fileshare.dao.MessageHandler;
import fr.fileshare.dao.UtilisateurHandler;
import fr.fileshare.models.Document;
import fr.fileshare.models.Historique;
import fr.fileshare.models.Message;
import fr.fileshare.models.Utilisateur;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abdelmoghitmadih
 */
public class Dashboard extends javax.swing.JFrame {
    
    private JFrame connexion;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }
    public Dashboard(JFrame connexion){
        this.connexion = connexion;
        this.connexion.setVisible(false);
        initComponents();
        this.setVisible(true);
        System.out.println("Im here");
        this.lblNomUtilisateur.setText(UtilisateurHandler.utilisateur.getNom().toUpperCase());
        this.lblUtilisateurImage.setIcon(new ImageIcon(getClass().getResource("/images/people2.png")));
        this.icone1.setIcon(new ImageIcon(getClass().getResource("/images/mesdocuments.png")));
        this.icone2.setIcon(new ImageIcon(getClass().getResource("/images/favoris.png")));
        this.icone3.setIcon(new ImageIcon(getClass().getResource("/images/historique.png")));
        this.icone4.setIcon(new ImageIcon(getClass().getResource("/images/nouveau.png")));
        this.icone5.setIcon(new ImageIcon(getClass().getResource("/images/message.png")));
        this.icone6.setIcon(new ImageIcon(getClass().getResource("/images/deconnexion.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        nav = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblNomUtilisateur = new javax.swing.JLabel();
        lblUtilisateurImage = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sideBar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        icone1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        icone2 = new javax.swing.JLabel();
        lblMesDocIcone = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        icone3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        icone4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        icone5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        icone6 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        icone8 = new javax.swing.JLabel();
        lblAccueilIcone3 = new javax.swing.JLabel();
        icone_message1 = new javax.swing.JLabel();
        icone9 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        tabPaneMain = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        MesDocuments = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        MesFavoris = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Historique = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        HistoriqueDoc = new javax.swing.JTable();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav.setBackground(new java.awt.Color(67, 142, 185));
        nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(98, 168, 209));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomUtilisateur.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblNomUtilisateur.setForeground(new java.awt.Color(255, 255, 255));
        lblNomUtilisateur.setToolTipText("");
        jPanel2.add(lblNomUtilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 20));
        jPanel2.add(lblUtilisateurImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bienvenue");
        jLabel10.setToolTipText("");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 9, 260, 40));

        nav.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 360, 70));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("File Share");
        nav.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        container.add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 70));

        sideBar.setBackground(new java.awt.Color(242, 242, 242));
        sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(88, 88, 88));
        jButton1.setText("Mes Documents");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));
        jPanel1.add(icone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        sideBar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 40));

        jSeparator3.setBackground(new java.awt.Color(229, 229, 229));
        sideBar.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 45, 250, 10));

        jPanel3.setBackground(new java.awt.Color(229, 229, 229));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(icone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));
        jPanel3.add(lblMesDocIcone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jButton3.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(88, 88, 88));
        jButton3.setText("Favoris");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        sideBar.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, 250, 40));

        jSeparator4.setBackground(new java.awt.Color(229, 229, 229));
        sideBar.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 88, 240, 10));

        jPanel4.setBackground(new java.awt.Color(229, 229, 229));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(icone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jButton4.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(88, 88, 88));
        jButton4.setText("Historique");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        sideBar.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 230, 40));

        jSeparator5.setBackground(new java.awt.Color(229, 229, 229));
        sideBar.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 130, 250, 10));

        jPanel5.setBackground(new java.awt.Color(229, 229, 229));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(icone4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jButton5.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jButton5.setForeground(new java.awt.Color(88, 88, 88));
        jButton5.setText("Nouveau Document");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        sideBar.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 138, -1, 40));

        jSeparator6.setBackground(new java.awt.Color(229, 229, 229));
        sideBar.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 173, 240, 10));

        jPanel6.setBackground(new java.awt.Color(229, 229, 229));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(icone5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jButton6.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jButton6.setForeground(new java.awt.Color(88, 88, 88));
        jButton6.setText("Messages");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        sideBar.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 181, 230, 40));

        jSeparator7.setBackground(new java.awt.Color(229, 229, 229));
        jSeparator7.setForeground(new java.awt.Color(229, 229, 229));
        sideBar.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 216, 240, 10));

        jPanel7.setBackground(new java.awt.Color(229, 229, 229));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jButton7.setForeground(new java.awt.Color(88, 88, 88));
        jButton7.setText("Deconnexion");
        jButton7.setToolTipText("");
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));
        jPanel7.add(icone6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        sideBar.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 224, 230, 40));

        jSeparator8.setBackground(new java.awt.Color(229, 229, 229));
        sideBar.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 258, 240, 10));
        sideBar.add(icone8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));
        sideBar.add(lblAccueilIcone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));
        sideBar.add(icone_message1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));
        sideBar.add(icone9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        container.add(sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 230, 670));

        main.setBackground(new java.awt.Color(255, 255, 255));

        MesDocuments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_auteur", "Intitulé", "Date de publication", "Dernière modification", "Tags", "Dernier éditeur", "Statut", "Id_doc"
            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    MesDocuments.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            MesDocumentsMouseClicked(evt);
        }
    });
    jScrollPane3.setViewportView(MesDocuments);

    jButton11.setText("Voir Document");
    jButton11.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton11ActionPerformed(evt);
        }
    });

    jLabel3.setBackground(new java.awt.Color(255, 0, 102));
    jLabel3.setForeground(new java.awt.Color(0, 0, 0));
    jLabel3.setText("                                 Action");

    jButton12.setText("Télécharger");
    jButton12.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton12ActionPerformed(evt);
        }
    });

    jButton13.setText("Modifier");
    jButton13.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton13ActionPerformed(evt);
        }
    });

    jButton14.setText("Supprimer");
    jButton14.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton14ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel8Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(236, 236, 236))
    );
    jPanel8Layout.setVerticalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel8Layout.createSequentialGroup()
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(238, 238, 238)
                    .addComponent(jLabel1))
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(49, Short.MAX_VALUE))
    );

    tabPaneMain.addTab("tab1", jPanel8);

    MesFavoris.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Id_auteur", "Intitulé", "Date de publication", "Dernière modification", "Tags", "Dernier éditeur", "Statut", "Id_doc"
        }
    )
    {public boolean isCellEditable(int row, int column){return false;}}
    );
    MesFavoris.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            MesFavorisMouseClicked(evt);
        }
    });
    jScrollPane4.setViewportView(MesFavoris);

    jLabel4.setBackground(new java.awt.Color(255, 0, 102));
    jLabel4.setForeground(new java.awt.Color(0, 0, 0));
    jLabel4.setText("                                 Action");

    jButton15.setText("Voir Document");
    jButton15.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton15ActionPerformed(evt);
        }
    });

    jButton16.setText("Télécharger");
    jButton16.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton16ActionPerformed(evt);
        }
    });

    jButton17.setText("Modifier");
    jButton17.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton17ActionPerformed(evt);
        }
    });

    jButton18.setText("Supprimer");
    jButton18.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton18ActionPerformed(evt);
        }
    });

    jButton19.setText("Retirer des favoris");
    jButton19.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton19ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(223, 223, 223))))
    );
    jPanel9Layout.setVerticalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(33, 33, 33))
    );

    tabPaneMain.addTab("tab2", jPanel9);

    Historique.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Id_auteur", "Intitulé", "Date de publication", "Dernière modification", "Tags", "Dernier éditeur", "Statut", "Id_doc"
        }
    )
    {public boolean isCellEditable(int row, int column){return false;}}
    );
    Historique.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            HistoriqueMouseClicked(evt);
        }
    });
    jScrollPane5.setViewportView(Historique);

    jLabel5.setBackground(new java.awt.Color(255, 0, 102));
    jLabel5.setForeground(new java.awt.Color(0, 0, 0));
    jLabel5.setText("                                 Action");

    jButton20.setText("Voir Document");
    jButton20.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton20ActionPerformed(evt);
        }
    });

    jButton21.setText("Modifier");
    jButton21.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton21ActionPerformed(evt);
        }
    });

    jButton22.setText("Voir Historique");
    jButton22.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton22ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
    jPanel10.setLayout(jPanel10Layout);
    jPanel10Layout.setHorizontalGroup(
        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel10Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(236, 236, 236))
    );
    jPanel10Layout.setVerticalGroup(
        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel10Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(89, Short.MAX_VALUE))
    );

    tabPaneMain.addTab("tab3", jPanel10);

    HistoriqueDoc.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Id_auteur", "Intitulé", "Date de modification", "Editeur", "Id_historique", "Id_doc"
        }
    )
    {public boolean isCellEditable(int row, int column){return false;}}
    );
    HistoriqueDoc.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            HistoriqueDocMouseClicked(evt);
        }
    });
    jScrollPane6.setViewportView(HistoriqueDoc);

    jButton24.setText("Revenir à cette Version");
    jButton24.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton24ActionPerformed(evt);
        }
    });

    jButton25.setText("Voir Version");
    jButton25.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton25ActionPerformed(evt);
        }
    });

    jLabel6.setBackground(new java.awt.Color(255, 0, 102));
    jLabel6.setForeground(new java.awt.Color(0, 0, 0));
    jLabel6.setText("                                 Action");

    javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
    jPanel11.setLayout(jPanel11Layout);
    jPanel11Layout.setHorizontalGroup(
        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
        .addGroup(jPanel11Layout.createSequentialGroup()
            .addGap(251, 251, 251)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(236, 236, 236))
    );
    jPanel11Layout.setVerticalGroup(
        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel11Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(129, Short.MAX_VALUE))
    );

    tabPaneMain.addTab("tab4", jPanel11);

    javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
    jPanel12.setLayout(jPanel12Layout);
    jPanel12Layout.setHorizontalGroup(
        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 734, Short.MAX_VALUE)
    );
    jPanel12Layout.setVerticalGroup(
        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 662, Short.MAX_VALUE)
    );

    tabPaneMain.addTab("tab5", jPanel12);

    javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
    main.setLayout(mainLayout);
    mainLayout.setHorizontalGroup(
        mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
            .addGap(0, 31, Short.MAX_VALUE)
            .addComponent(tabPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    mainLayout.setVerticalGroup(
        mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(tabPaneMain)
    );

    container.add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 770, 670));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        UtilisateurHandler.utilisateur = null;
        this.setVisible(false);
        connexion.setVisible(true);
        this.dispose();
            
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        UtilisateurHandler.utilisateur = null;
        connexion.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        /* Historique */
        tabPaneMain.setEnabledAt(0, false);
        tabPaneMain.setEnabledAt(1, false);
        tabPaneMain.setEnabledAt(2, false);
        tabPaneMain.setEnabledAt(3, false);
        tabPaneMain.setEnabledAt(4, false);
        
        tabPaneMain.setSelectedIndex(2);
        IDocumentHandler documentHandler = new DocumentHandler();
        List<Document> documents = documentHandler.getMesDocuments(UtilisateurHandler.utilisateur.getId());
        
        DefaultTableModel model = (DefaultTableModel) Historique.getModel();
        /* Supprimer les données du JTable avant chaque remplissage */
        model.setRowCount(0);
        
        Object rowData[] = new Object[8];
           
        /* Cacher les colonne id_documents et id_auteur */
        Historique.getColumnModel().getColumn(0).setMinWidth(0);
        Historique.getColumnModel().getColumn(0).setMaxWidth(0);
        Historique.getColumnModel().getColumn(0).setWidth(0);
        Historique.getColumnModel().getColumn(7).setMinWidth(0);
        Historique.getColumnModel().getColumn(7).setMaxWidth(0);
        Historique.getColumnModel().getColumn(7).setWidth(0);
        
        for (int i = 0; i < documents.size(); i++) {
            rowData[0] = documents.get(i).getAuteur().getId();
            rowData[1] = documents.get(i).getIntitule();
            rowData[2] = documents.get(i).getDatePublixation();
            rowData[3] = documents.get(i).getDateDerniereModif();
            rowData[4] = documents.get(i).getTag();
            rowData[5] = documents.get(i).getDernierEditeur().getNom();
            switch (documents.get(i).getStatus()) {
                case 0:
                    rowData[6] = "Public";
                    break;
                case 1:
                    rowData[6] = "Privé";
                    break;
                case 2:
                    Set<Utilisateur> user = documents.get(i).getUtilisateursAvecDroit();
                    String partager_avec = "Partagé avec ";
                    for (Utilisateur utilisateur : user) {
                        if (utilisateur.getId() == UtilisateurHandler.utilisateur.getId()) {
                            partager_avec += "moi ";
                        }
                        else {
                            partager_avec += utilisateur.getNom() + " ";
                        }
                    }   rowData[6] = partager_avec;
                    break;
                default:
                    break;
            }
            rowData[7] = documents.get(i).getId();
            model.addRow(rowData);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        /* Mes favoris */
        tabPaneMain.setEnabledAt(0, false);
        tabPaneMain.setEnabledAt(1, false);
        tabPaneMain.setEnabledAt(2, false);
        tabPaneMain.setEnabledAt(3, false);
        tabPaneMain.setEnabledAt(4, false);
        
        tabPaneMain.setSelectedIndex(1);
        IDocumentHandler documentHandler = new DocumentHandler();
        List<Document> documents = documentHandler.getDocumentsFavoris(UtilisateurHandler.utilisateur, 0, 400);

        DefaultTableModel model = (DefaultTableModel) MesFavoris.getModel();
        /* Supprimer les données du JTable avant chaque remplissage */
        model.setRowCount(0);

        Object rowData[] = new Object[8];
           
        /* Cacher les colonne id_documents et id_auteur */
        MesFavoris.getColumnModel().getColumn(0).setMinWidth(0);
        MesFavoris.getColumnModel().getColumn(0).setMaxWidth(0);
        MesFavoris.getColumnModel().getColumn(0).setWidth(0);
        MesFavoris.getColumnModel().getColumn(7).setMinWidth(0);
        MesFavoris.getColumnModel().getColumn(7).setMaxWidth(0);
        MesFavoris.getColumnModel().getColumn(7).setWidth(0);

        for (int i = 0; i < documents.size(); i++) {
            rowData[0] = documents.get(i).getAuteur().getId();
            rowData[1] = documents.get(i).getIntitule();
            rowData[2] = documents.get(i).getDatePublixation();
            rowData[3] = documents.get(i).getDateDerniereModif();
            rowData[4] = documents.get(i).getTag();
            rowData[5] = documents.get(i).getDernierEditeur().getNom();
            switch (documents.get(i).getStatus()) {
                case 0:
                    rowData[6] = "Public";
                    break;
                case 1:
                    rowData[6] = "Privé";
                    break;
                case 2:
                    Set<Utilisateur> user = documents.get(i).getUtilisateursAvecDroit();
                    String partager_avec = "Partagé avec ";
                    for (Utilisateur utilisateur : user) {
                        if (utilisateur.getId() == UtilisateurHandler.utilisateur.getId()) {
                            partager_avec += "moi ";
                        }
                        else {
                            partager_avec += utilisateur.getNom() + " ";
                        }
                    }   rowData[6] = partager_avec;
                    break;
                default:
                    break;
            }
            rowData[7] = documents.get(i).getId();
            model.addRow(rowData);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /* Mes documents */
        tabPaneMain.setEnabledAt(0, false);
        tabPaneMain.setEnabledAt(1, false);
        tabPaneMain.setEnabledAt(2, false);
        tabPaneMain.setEnabledAt(3, false);
        tabPaneMain.setEnabledAt(4, false);
        
        tabPaneMain.setSelectedIndex(0);
        IDocumentHandler documentHandler = new DocumentHandler();
        List<Document> documents = documentHandler.getMesDocuments(UtilisateurHandler.utilisateur.getId());
        
        DefaultTableModel model = (DefaultTableModel) MesDocuments.getModel();
        /* Supprimer les données du JTable avant chaque remplissage */
        model.setRowCount(0);
        
        Object rowData[] = new Object[8];
           
        /* Cacher les colonne id_documents et id_auteur */
        MesDocuments.getColumnModel().getColumn(0).setMinWidth(0);
        MesDocuments.getColumnModel().getColumn(0).setMaxWidth(0);
        MesDocuments.getColumnModel().getColumn(0).setWidth(0);
        MesDocuments.getColumnModel().getColumn(7).setMinWidth(0);
        MesDocuments.getColumnModel().getColumn(7).setMaxWidth(0);
        MesDocuments.getColumnModel().getColumn(7).setWidth(0);
        
        for (int i = 0; i < documents.size(); i++) {
            rowData[0] = documents.get(i).getAuteur().getId();
            rowData[1] = documents.get(i).getIntitule();
            rowData[2] = documents.get(i).getDatePublixation();
            rowData[3] = documents.get(i).getDateDerniereModif();
            rowData[4] = documents.get(i).getTag();
            rowData[5] = documents.get(i).getDernierEditeur().getNom();
            switch (documents.get(i).getStatus()) {
                case 0:
                    rowData[6] = "Public";
                    break;
                case 1:
                    rowData[6] = "Privé";
                    break;
                case 2:
                    Set<Utilisateur> user = documents.get(i).getUtilisateursAvecDroit();
                    String partager_avec = "Partagé avec ";
                    for (Utilisateur utilisateur : user) {
                        if (utilisateur.getId() == UtilisateurHandler.utilisateur.getId()) {
                            partager_avec += "moi ";
                        }
                        else {
                            partager_avec += utilisateur.getNom() + " ";
                        }
                    }   rowData[6] = partager_avec;
                    break;
                default:
                    break;
            }
            rowData[7] = documents.get(i).getId();
            model.addRow(rowData);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        /* Voir Historique Document */
        
        DefaultTableModel model = (DefaultTableModel) Historique.getModel();
        int i = Historique.getSelectedRow();
        
        int id_doc = Integer.parseInt(model.getValueAt(i, 7).toString());
        HistoriqueHandler historiqueHandler = new HistoriqueHandler();
        List<Historique> historique = historiqueHandler.getHistorique(UtilisateurHandler.utilisateur.getId(), id_doc, 0, 400);
        
        if (i >= 0) {
            tabPaneMain.setSelectedIndex(3);
        
            tabPaneMain.setEnabledAt(0, false);
            tabPaneMain.setEnabledAt(1, false);
            tabPaneMain.setEnabledAt(2, false);
            tabPaneMain.setEnabledAt(3, false);
            tabPaneMain.setEnabledAt(4, false);

            DefaultTableModel model1 = (DefaultTableModel) HistoriqueDoc.getModel();
            /* Supprimer les données du JTable avant chaque remplissage */
            model1.setRowCount(0);

            Object rowData[] = new Object[8];

            /* Cacher les colonne id_documents et id_auteur */
            HistoriqueDoc.getColumnModel().getColumn(0).setMinWidth(0);
            HistoriqueDoc.getColumnModel().getColumn(0).setMaxWidth(0);
            HistoriqueDoc.getColumnModel().getColumn(0).setWidth(0);
            HistoriqueDoc.getColumnModel().getColumn(4).setMinWidth(0);
            HistoriqueDoc.getColumnModel().getColumn(4).setMaxWidth(0);
            HistoriqueDoc.getColumnModel().getColumn(4).setWidth(0);

            for (int l = 0; l < historique.size(); l++) {
                rowData[0] = historique.get(l).getDocument().getAuteur().getId();
                rowData[1] = historique.get(l).getDocument().getIntitule();
                rowData[2] = historique.get(l).getDateModif();
                rowData[3] = historique.get(l).getEditeur().getNom();
                rowData[4] = historique.get(l).getId();
                rowData[5] = historique.get(l).getDocument().getId();
                model1.addRow(rowData);
            }
        }
        else {
            System.out.println("Aucun Document n'a été selectionné !");
        }
        
        

    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        /* Modifier Document Historique */

        DefaultTableModel model = (DefaultTableModel) Historique.getModel();
        int i = Historique.getSelectedRow();

        if (i >= 0) {
            System.out.println("ID du document à modifier : " + Integer.parseInt(model.getValueAt(i, 7).toString()));
        }
        else {
            System.out.println("Aucun Document n'a été selectionné !");
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        /* Voir Document Historique */

        DefaultTableModel model = (DefaultTableModel) Historique.getModel();
        int i = Historique.getSelectedRow();

        if (i >= 0) {
            System.out.println("ID du document à consulter : " + Integer.parseInt(model.getValueAt(i, 7).toString()));
        }
        else {
            System.out.println("Aucun Document n'a été selectionné !");
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void HistoriqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoriqueMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HistoriqueMouseClicked

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        /* Retirer Des Favoris */

        DefaultTableModel model = (DefaultTableModel) MesFavoris.getModel();
        int i = MesFavoris.getSelectedRow();

        if (i >= 0) {
            /* Verifier si l'utilisateur connecté est l'auteur du document avant suppression */
            if (Integer.parseInt(model.getValueAt(i, 0).toString()) == UtilisateurHandler.utilisateur.getId()) {
                int confirmation = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment retirer ce document de vos favoris ?", "Confirmation retrait favoris", JOptionPane.YES_NO_OPTION);
                if (confirmation == 0) {
                    model.removeRow(i);
                    DocumentHandler documentHandler = new DocumentHandler();
                    documentHandler.supprimerFavoris(UtilisateurHandler.utilisateur.getId(), Integer.parseInt(model.getValueAt(i, 7).toString()));
                }
            }
        }
        else {
            System.out.println("Aucun Document n'a été selectionné !");
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        /* Suppression Document Favoris */

        DefaultTableModel model = (DefaultTableModel) MesFavoris.getModel();
        int i = MesFavoris.getSelectedRow();

        if (i >= 0) {
            /* Verifier si l'utilisateur connecté est l'auteur du document avant suppression */
            if (Integer.parseInt(model.getValueAt(i, 0).toString()) == UtilisateurHandler.utilisateur.getId()) {
                int confirmation = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer ce document ?", "Confirmation suppression", JOptionPane.YES_NO_OPTION);
                if (confirmation == 0) {
                    model.removeRow(i);
                    DocumentHandler documentHandler = new DocumentHandler();
                    Document document = documentHandler.get(Integer.parseInt(model.getValueAt(i, 7).toString()));
                    documentHandler.delete(document);
                }
            }
        }
        else {
            System.out.println("Aucun Document n'a été selectionné !");
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        /* Modifier Document Favoris */

        DefaultTableModel model = (DefaultTableModel) MesFavoris.getModel();
        int i = MesFavoris.getSelectedRow();

        if (i >= 0) {
            System.out.println("ID du document à modifier : " + Integer.parseInt(model.getValueAt(i, 7).toString()));
        }
        else {
            System.out.println("Aucun Document n'a été selectionné !");
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        /* Téléchargement Document Favoris */
        int i = MesFavoris.getSelectedRow();

        if (i >= 0) {
            JFileChooser fc = new JFileChooser();
            fc.setDialogTitle("Téléchargement Document");
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            if (fc.showOpenDialog(jButton12) == JFileChooser.APPROVE_OPTION) {

            }
            System.out.println("Emplacement choisi : " + fc.getSelectedFile().getAbsolutePath());
        }
        else {
            System.out.println("Aucun Document n'a été selectionné !");
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        /* Voir Document Favoris */

        DefaultTableModel model = (DefaultTableModel) MesFavoris.getModel();
        int i = MesFavoris.getSelectedRow();

        if (i >= 0) {
            System.out.println("ID du document à consulter : " + Integer.parseInt(model.getValueAt(i, 7).toString()));
        }
        else {
            System.out.println("Aucun Document n'a été selectionné !");
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void MesFavorisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MesFavorisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MesFavorisMouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        /* Suppression */

        DefaultTableModel model = (DefaultTableModel) MesDocuments.getModel();
        int i = MesDocuments.getSelectedRow();

        if (i >= 0) {
            /* Verifier si l'utilisateur connecté est l'auteur du document avant suppression */
            if (Integer.parseInt(model.getValueAt(i, 0).toString()) == UtilisateurHandler.utilisateur.getId()) {
                int confirmation = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer ce document ?", "Confirmation suppression", JOptionPane.YES_NO_OPTION);
                if (confirmation == 0) {
                    model.removeRow(i);
                    DocumentHandler documentHandler = new DocumentHandler();
                    Document document = documentHandler.get(Integer.parseInt(model.getValueAt(i, 7).toString()));
                    documentHandler.delete(document);
                }
            }
        }
        else {
            System.out.println("Aucun Document n'a été selectionné !");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        /* Modifier Document */

        DefaultTableModel model = (DefaultTableModel) MesDocuments.getModel();
        int i = MesDocuments.getSelectedRow();

        if (i >= 0) {
            System.out.println("ID du document à modifier : " + Integer.parseInt(model.getValueAt(i, 7).toString()));
        }
        else {
            System.out.println("Aucun Document n'a été selectionné !");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        /* Téléchargement */
        int i = MesDocuments.getSelectedRow();

        if (i >= 0) {
            JFileChooser fc = new JFileChooser();
            fc.setDialogTitle("Téléchargement Document");
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            if (fc.showOpenDialog(jButton12) == JFileChooser.APPROVE_OPTION) {

            }
            System.out.println("Emplacement choisi : " + fc.getSelectedFile().getAbsolutePath());
        }
        else {
            System.out.println("Aucun Document n'a été selectionné !");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        /* Voir Document */

        DefaultTableModel model = (DefaultTableModel) MesDocuments.getModel();
        int i = MesDocuments.getSelectedRow();

        if (i >= 0) {
            System.out.println("ID du document à consulter : " + Integer.parseInt(model.getValueAt(i, 7).toString()));
        }
        else {
            System.out.println("Aucun Document n'a été selectionné !");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void MesDocumentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MesDocumentsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) MesDocuments.getModel();
        int i = MesDocuments.getSelectedRow();
        //jButton11.setActionCommand(Integer.toString(model.getValueAt(i, 1)));
    }//GEN-LAST:event_MesDocumentsMouseClicked

    private void HistoriqueDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoriqueDocMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HistoriqueDocMouseClicked

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        /* Revenir à une version depuis historique */
        
        DefaultTableModel model = (DefaultTableModel) HistoriqueDoc.getModel();
        int i = HistoriqueDoc.getSelectedRow();
        
        if (i >= 0) {
            /* Verifier si l'utilisateur connecté est l'auteur du document avant suppression */
            if (Integer.parseInt(model.getValueAt(i, 0).toString()) == UtilisateurHandler.utilisateur.getId()) {
                int confirmation = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment Revenir à cette version ?", "Confirmation retour version précédente", JOptionPane.YES_NO_OPTION);
                if (confirmation == 0) {
                    
                    /* Récuperer l'historique */
                    HistoriqueHandler historiqueHandler = new HistoriqueHandler();
                    Historique historique = historiqueHandler.get(Integer.parseInt(model.getValueAt(i, 4).toString()));
                    
                    /* Récupérer le document */
                    DocumentHandler documentHandler = new DocumentHandler();
                    Document document = documentHandler.get(Integer.parseInt(model.getValueAt(i, 5).toString()));
                }
            }
        }
        else {
            System.out.println("Aucun Document n'a été selectionné !");
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        /* Voir Version Historique */

        DefaultTableModel model = (DefaultTableModel) HistoriqueDoc.getModel();
        int i = HistoriqueDoc.getSelectedRow();

        if (i >= 0) {
            System.out.println("ID de la version du document à consulter : " + Integer.parseInt(model.getValueAt(i, 4).toString()));
        }
        else {
            System.out.println("Aucun Document n'a été selectionné !");
        }
    }//GEN-LAST:event_jButton25ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Historique;
    private javax.swing.JTable HistoriqueDoc;
    private javax.swing.JTable MesDocuments;
    private javax.swing.JTable MesFavoris;
    private javax.swing.JPanel container;
    private javax.swing.JLabel icone1;
    private javax.swing.JLabel icone2;
    private javax.swing.JLabel icone3;
    private javax.swing.JLabel icone4;
    private javax.swing.JLabel icone5;
    private javax.swing.JLabel icone6;
    private javax.swing.JLabel icone8;
    private javax.swing.JLabel icone9;
    private javax.swing.JLabel icone_message1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblAccueilIcone3;
    private javax.swing.JLabel lblMesDocIcone;
    private javax.swing.JLabel lblNomUtilisateur;
    private javax.swing.JLabel lblUtilisateurImage;
    private javax.swing.JPanel main;
    private javax.swing.JPanel nav;
    private javax.swing.JPanel sideBar;
    private javax.swing.JTabbedPane tabPaneMain;
    // End of variables declaration//GEN-END:variables
}
