/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.fileshare.views;

import java.awt.Color;

/**
 *
 * @author abdelmoghitmadih
 */
public class MessageBox extends javax.swing.JFrame {

    public static int SUCCESS = 0;
    public static int ERROR = 1;
    public static int WARNING = 2;
    public static int INFO = 3;
    
    public MessageBox(){
    }
    /**
     * Creates new form MessageBox
     */
    public MessageBox(String message, int STATUS) {
        initComponents();
        switch (STATUS) {
            case 0://success
                this.setBackground(new Color(223,240,216));
                this.lblTxt.setForeground(new Color(60,118,61));
                this.pnlBtn.setBackground(new Color(60,118,61));
                this.btnOk.setForeground(new Color(223,240,216));
                break;
            case 1://error
                this.setBackground(new Color(242,222,222));
                this.lblTxt.setForeground(new Color(169,68,66));
                this.pnlBtn.setBackground(new Color(169,68,66));
                this.btnOk.setForeground(new Color(242,222,222));
                break;
            case 2://warning
                this.setBackground(new Color(252,248,227));
                this.lblTxt.setForeground(new Color(138,109,59));
                this.pnlBtn.setBackground(new Color(138,109,59));
                this.btnOk.setForeground(new Color(252,248,227));
                break;
            case 3://info
                this.setBackground(new Color(217,237,247));
                this.lblTxt.setForeground(new Color(49,112,143));
                this.pnlBtn.setBackground(new Color(49,112,143));
                this.btnOk.setForeground(new Color(217,237,247));
                break;
        }
        this.lblTxt.setText(message);
        this.setVisible(true);
    }
    public static void messageBox(String msg , int status){
        new MessageBox(msg, status);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTxt = new javax.swing.JLabel();
        pnlBtn = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(217, 237, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTxt.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lblTxt.setForeground(new java.awt.Color(138, 109, 59));
        lblTxt.setText("Votre compte a ete cree avec succes");
        lblTxt.setToolTipText("");
        jPanel1.add(lblTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        pnlBtn.setBackground(new java.awt.Color(49, 112, 143));
        pnlBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOk.setForeground(new java.awt.Color(217, 237, 247));
        btnOk.setText("OK");
        btnOk.setBorderPainted(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        pnlBtn.add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        jPanel1.add(pnlBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, 40));

        jButton2.setText("X");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 60, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 215));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessageBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessageBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessageBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessageBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessageBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTxt;
    private javax.swing.JPanel pnlBtn;
    // End of variables declaration//GEN-END:variables
}
